// <auto-generated />
namespace ITAssetsDatabase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class April2017 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(April2017));
        
        string IMigrationMetadata.Id
        {
            get { return "201704101109407_April2017"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
